# Generated by Django 3.2.14 on 2022-07-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст поста')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('pub_date', models.DateTimeField(verbose_name='Дата публикации')),
                ('count_likes', models.IntegerField(verbose_name='Количество лайков')),
            ],
        ),
        migrations.DeleteModel(
            name='Riddle',
        ),
    ]
